:mod:`pydaymet.exceptions`
==========================

.. py:module:: pydaymet.exceptions

.. autoapi-nested-parse::

   Customized PyDaymet exceptions.



Module Contents
---------------

.. py:exception:: ZeroMatched

   Bases: :class:`ValueError`

   Exception raised when a function argument is missing.

   .. py:class:: args


   .. method:: with_traceback()

      Exception.with_traceback(tb) --
      set self.__traceback__ to tb and return self.



.. py:exception:: InvalidInputValue(inp: str, valid_inputs: Union[List[Any], Generator[str, None, None]])

   Bases: :class:`Exception`

   Exception raised for invalid input.

   :param inp: Name of the input parameter
   :type inp: str
   :param valid_inputs: List of valid inputs
   :type valid_inputs: tuple

   .. py:class:: args


   .. method:: with_traceback()

      Exception.with_traceback(tb) --
      set self.__traceback__ to tb and return self.



.. py:exception:: InvalidInputType(arg: str, valid_type: str, example: Optional[str] = None)

   Bases: :class:`Exception`

   Exception raised when a function argument type is invalid.

   :param arg: Name of the function argument
   :type arg: str
   :param valid_type: The valid type of the argument
   :type valid_type: str
   :param example: An example of a valid form of the argument, defaults to None.
   :type example: str, optional

   .. py:class:: args


   .. method:: with_traceback()

      Exception.with_traceback(tb) --
      set self.__traceback__ to tb and return self.



.. py:exception:: InvalidInputRange

   Bases: :class:`ValueError`

   Exception raised when a function argument is not in the valid range.

   .. py:class:: args


   .. method:: with_traceback()

      Exception.with_traceback(tb) --
      set self.__traceback__ to tb and return self.



.. py:exception:: MissingItems(missing: List[str])

   Bases: :class:`Exception`

   Exception raised when a required item is missing.

   :param missing: A list of missing items.
   :type missing: list

   .. py:class:: args


   .. method:: with_traceback()

      Exception.with_traceback(tb) --
      set self.__traceback__ to tb and return self.



